#: Minimal Theme
foreground            #e0e0e0
background            #1a1a1a
background_opacity    0.95
selection_foreground  #000000
selection_background  #ffffff

#: Color Table
color0      #1a1a1a
color8      #666666
color1      #ff3333
color9      #ff6666
color2      #33ff33
color10     #66ff66
color3      #ffff33
color11     #ffff66
color4      #3399ff
color12     #66ccff
color5      #ff33ff
color13     #ff66ff
color6      #33ffff
color14     #66ffff
color7      #e0e0e0
color15     #ffffff